#
#
# List of all required and authorized motors (motors ids)
#
# (please read carefuly before editing anything)
#
# You should not need to edit this file, unless 
#   - you want to debug on some detached motors
#   - you are developing new features
#   - you really know what you are doing
#
#

can_required_motors: # Axis 1-4 or Niryo One (stepper 1 -> id 1, stepper 2 -> id 2, ...)
    # Edit only for debug purposes (ex : you want to test some motors separately and detached from the robot)
    # --> Commented ids will make associated motor disable (and thus not trigger an error if not connected)
    # Before editing, please be sure that you know what you're doing  
    - 1 # Axis 1 enabled if not commented
    - 2 # Axis 2 enabled if not commented
    - 3 # Axis 3 enabled if not commented
    - 4 # Axis 4 enabled if not commented

dxl_required_motors: # axis 5 and 6 of Niryo One.
    # !!! ORDER IS VERY IMPORTANT, YOU MAY DAMAGE SOME MOTORS OR THE ROBOT IF YOU PUT WRONG VALUES/ORDER HERE !!!
    # --> Edit only if you decide to change a Dynamixel motor id by yourself, and you want to use it instead of default id
    # --> first value is servo 5_1 id, second is servo 5_2 id, third is servo 6 id
    # This is not the same as for can_required_motors, here you need to let 3 ids, and thus have 3 motors connected
    # Before editing, please be sure that you know what you're doing
    - 4 # -> id of Axis 5_1
    - 5 # -> id of Axis 5_2
    - 6 # -> id of Axis 6

dxl_authorized_motors: # here include all Dynamixel tools that can possibly be attached to Niryo One
    - 11 # id of Gripper 1
    - 12 # id of Gripper 2
    - 13 # id of Gripper 3
    - 31 # if of Vacuum Pump 1
